import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#fff', padding: 24 },
  categoryScroll: { backgroundColor: '#fff', paddingVertical: 10, paddingHorizontal: 8, maxHeight: 55 },
  categoryBtn: { backgroundColor: '#FF4500', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginRight: 8 },
  categoryBtnActive: { backgroundColor: '#cc3300' },
  categoryText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  card: { backgroundColor: '#fff', borderRadius: 20, marginBottom: 16, shadowColor: '#FF4500', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 4, overflow: 'hidden' },
  cardImage: { width: '100%', height: 200 },
  cardImagePlaceholder: { width: '100%', height: 180, backgroundColor: '#f8f8f8', justifyContent: 'center', alignItems: 'center' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  discountBadge: { backgroundColor: '#FF4500', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 4 },
  discountText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  cardCategory: { color: '#FF4500', fontSize: 11, fontWeight: '700', letterSpacing: 0.5, marginBottom: 4, textTransform: 'uppercase' },
  cardTitle: { fontSize: 17, fontWeight: '700', color: '#1a1a1a', marginBottom: 8, lineHeight: 22 },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  newPrice: { fontSize: 22, fontWeight: '800', color: '#fff' },
  oldPrice: { fontSize: 14, color: 'rgba(255,255,255,0.7)', textDecorationLine: 'line-through' },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between' },
  storeName: { color: '#FF4500', fontSize: 12, fontWeight: '600' },
  cityName: { color: '#999', fontSize: 12 },
  searchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', margin: 12, borderRadius: 16, paddingHorizontal: 16, paddingVertical: 12, elevation: 3, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 8 },
  searchInput: { flex: 1, fontSize: 16, color: '#1a1a1a' },
  bigBtn: { backgroundColor: '#FF4500', paddingVertical: 16, paddingHorizontal: 24, borderRadius: 16, width: '100%', alignItems: 'center', shadowColor: '#FF4500', shadowOpacity: 0.2, shadowRadius: 8, elevation: 3 },
  bigBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  input: { backgroundColor: '#f8f8f8', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, marginBottom: 14, color: '#1a1a1a', borderWidth: 1.5, borderColor: '#f0f0f0' },
  label: { fontSize: 14, fontWeight: '600', color: '#444', marginBottom: 6 },
  imagePicker: { backgroundColor: '#f8f8f8', borderRadius: 18, height: 180, justifyContent: 'center', alignItems: 'center', marginBottom: 20, borderWidth: 2, borderColor: '#FF4500', borderStyle: 'dashed', overflow: 'hidden' },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  statCard: { flex: 1, backgroundColor: '#fff', borderRadius: 18, padding: 16, alignItems: 'center', elevation: 3, shadowColor: '#FF4500', shadowOpacity: 0.08, shadowRadius: 8 },
  statNumber: { fontSize: 32, fontWeight: '800', color: '#FF4500' },
  statLabel: { fontSize: 12, color: '#999', textAlign: 'center', marginTop: 4 },
  dealRow: { backgroundColor: '#fff', borderRadius: 14, padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center', elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 6 },
  sortBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: '#f0f0f0' },
  sortBtnActive: { backgroundColor: '#FF4500' },
  sortText: { fontSize: 13, color: '#666', fontWeight: '600' },
  sortTextActive: { color: '#fff' },
  banner: { margin: 12, borderRadius: 22, padding: 20, flexDirection: 'row', alignItems: 'center', minHeight: 130 },
  bannerTitle: { fontSize: 22, fontWeight: '800', color: '#fff', marginBottom: 6 },
  bannerSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.85)', marginBottom: 10 },
  bannerBadge: { backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 12, alignSelf: 'flex-start' },
});
